// ---  file automatically generated by TaskControl --- 
// int reward_tone_freq = 12000;
// int trial_avail_cue_freq = 8000;
// int punish_tone_freq = 6000;

int stim_tone_freq = 10000;
int reward_cue_freq = 12000;

unsigned long autostart_dur = 1000;
unsigned long choice_dur = 2000;
unsigned long timeout_dur = 4000;
unsigned long ITI_dur = 5000;

unsigned long reward_magnitude = 5;
float valve_ul_ms = 0.07487586;

unsigned long reward_available_dur = 500;

float X_left_thresh = -0.5;
float X_right_thresh = 0.5;