// ---  file automatically generated by TaskControl --- 
int reward_tone_freq = 12000;
int reward_cue_freq = 12000;
int trial_avail_cue_freq = 10000;
int punish_tone_freq = 6000;
unsigned long ITI_dur = 5000;
unsigned long timeout_dur = 4000;
unsigned long reward_valve_dur = 70;
unsigned long reward_magnitude = 10;
unsigned long fix_dur_min = 500;
unsigned long fix_dur = 1500;
unsigned long fix_dur_target = 3000;
float fix_increment = 0.03;
float fix_decrement = 0.01;
unsigned long reward_available_dur = 500;