// ---  file automatically generated by TaskControl --- 
int punish_tone_freq = 6000;

int reward_cue_freq = 12000;
int reward_tone_freq = 12000;

unsigned long trial_entry_pause_dur_min = 500;
unsigned long trial_entry_pause_dur_max = 1000;
unsigned long choice_dur = 5000;
unsigned long ITI_dur_min = 1000;
unsigned long ITI_dur_max = 3000;
unsigned long min_fix_dur = 2000;
unsigned long reward_magnitude = 10;
float valve_ul_ms = 0.07487586;

unsigned long reward_available_dur = 1000;

bool forced_alternating = false;

float X_start_thresh = 1000;
float X_thresh = 1000;
float X_target_thresh = 2500;
float X_increment = 0.03;
float X_decrement = -0.01;

float Y_start_thresh = 2000;
float Y_thresh = 2000;
float Y_target_thresh = 1000;
float Y_increment = 0.01;
float Y_decrement = -0.03;