// ---  file automatically generated by TaskControl --- 
int punish_tone_freq = 6000;

int reward_cue_freq = 12000;
int reward_tone_freq = 12000;

unsigned long trial_entry_pause_dur_min = 500;
unsigned long trial_entry_pause_dur_max = 1000;
unsigned long choice_dur = 7500;
unsigned long ITI_dur_min = 5000;
unsigned long ITI_dur_max = 7500;
unsigned long min_fix_dur = 1000;
unsigned long reward_magnitude = 5;
float valve_ul_ms = 0.07487586;

unsigned long reward_available_dur = 1000;

float X_left_thresh = -2000;
float X_right_thresh = 2000;

float Y_back_thresh = -2000;
float Y_front_thresh = 2000;