// ---  file automatically generated by TaskControl --- 

//Animal: 123

int incorrect_choice_cue_freq = 6000;
int correct_choice_cue_freq = 12000;
unsigned long choice_dur = 5000;
unsigned long ITI_dur_min = 1000;
unsigned long ITI_dur_max = 3000;
unsigned long min_fix_dur = 2000;
unsigned long reward_magnitude = 10;
// unsigned long trial_t_gap = 1000;
float valve_ul_ms = 0.07487586;
unsigned long reward_available_dur = 1000;

float X_thresh = 1000.0;
float X_thresh_start = 1000.0;
float X_thresh_target = 2500.0;
float X_thresh_increment = 0.03;
float X_thresh_decrement = -0.01;
float Y_thresh = 2000.0;
float Y_thresh_start = 2000.0;
float Y_thresh_target = 1500.0;
float Y_thresh_increment = 0.01;
float Y_thresh_decrement = -0.03;

float bias = 0.5;
