// ---  file automatically generated by TaskControl --- 
int reward_tone_freq = 12000;
int reward_cue_freq = 12000;
int trial_avail_cue_freq = 8000;
int punish_cue_freq = 6000;
unsigned long ITI_dur = 7500;
unsigned long reward_magnitude = 10;
float valve_ul_ms = 0.07487586;
unsigned long reward_available_dur = 1000;
float reward_prob = 0.5;

