// ---  file automatically generated by TaskControl --- 
int reward_tone_freq = 12000;
int reward_cue_freq = 12000;
unsigned long ITI_dur_min = 2500;
unsigned long ITI_dur_max = 7500;
unsigned long reward_magnitude = 10;
float valve_ul_ms = 0.07487586;
unsigned long reward_available_dur = 1000;

